/* ===========================================================================
   Plantilla base del programa ISEL.
   Todo lo que está aquí es solo el punto de partida: al crear un colaborador
   esta plantilla se copia a su expediente y a partir de ahí el mentor puede
   editar, agregar o quitar semanas, tareas, competencias, KPIs y criterios.
   =========================================================================== */

export const NIVELES = [
  { n: 1, etiqueta: "Conocimiento insuficiente", conducta: "No conoce el concepto ni lo aplica. Requiere que alguien más ejecute la actividad por él." },
  { n: 2, etiqueta: "Conoce, requiere supervisión", conducta: "Explica el concepto pero al ejecutar necesita guion, revisión previa y corrección posterior en cada intento." },
  { n: 3, etiqueta: "Ejecuta con apoyo ocasional", conducta: "Ejecuta la actividad completa solo, con calidad aceptable, pidiendo apoyo en casos complejos o poco frecuentes." },
  { n: 4, etiqueta: "Ejecuta de forma autónoma", conducta: "Ejecuta con calidad consistente sin supervisión, adapta el enfoque al cliente y sostiene el resultado en el tiempo." },
  { n: 5, etiqueta: "Domina y enseña", conducta: "Obtiene resultados por encima del estándar, corrige su propio desempeño y puede entrenar a otro vendedor en la competencia." },
];

export const CORTES = [
  { id: "ini", nombre: "Inicial" }, { id: "m1", nombre: "Mes 1" }, { id: "m2", nombre: "Mes 2" },
  { id: "m3", nombre: "Mes 3" }, { id: "m4", nombre: "Mes 4" }, { id: "m5", nombre: "Mes 5" },
];

export const TIPOS_VISITA = [
  { id: "observa", nombre: "Observa al mentor" },
  { id: "acompanado", nombre: "Participa acompañado" },
  { id: "lidera", nombre: "Lidera con acompañamiento" },
  { id: "autonoma", nombre: "Lidera solo" },
];

export const MADUREZ = [
  { n: 1, nombre: "Un contacto", desc: "ISEL habla con una sola persona, normalmente compras o un técnico. La relación depende de esa persona." },
  { n: 2, nombre: "Red de contactos", desc: "Hay contacto activo con al menos tres áreas: mantenimiento, ingeniería y producción o seguridad." },
  { n: 3, nombre: "Proveedor frecuente", desc: "La planta compra de forma recurrente varias líneas y ISEL participa en la mayoría de sus requerimientos." },
  { n: 4, nombre: "Proveedor estratégico", desc: "ISEL participa en la planeación de proyectos, se le consulta antes de que exista requisición y hay acuerdos anuales o marcos." },
];

/* Tipos de criterio de graduación. El campo `fuente` le dice a la aplicación
   de dónde sacar el valor real; `meta` es el número que el mentor puede mover. */
export const FUENTES_CRITERIO = [
  { id: "scorecard", nombre: "Scorecard ponderado del último corte", formato: "decimal" },
  { id: "criticas", nombre: "Competencias críticas por debajo del nivel requerido", formato: "menor" },
  { id: "visitas", nombre: "Visitas acumuladas", formato: "entero" },
  { id: "visitas_solo", nombre: "Visitas lideradas solo", formato: "entero" },
  { id: "opps", nombre: "Oportunidades detectadas", formato: "entero" },
  { id: "pipeline", nombre: "Pipeline abierto", formato: "dinero" },
  { id: "pipeline_cal", nombre: "Pipeline calificado", formato: "dinero" },
  { id: "ventas", nombre: "Ventas cerradas", formato: "dinero" },
  { id: "cuentas", nombre: "Cuentas mapeadas", formato: "entero" },
  { id: "planes", nombre: "Account Plans aprobados", formato: "entero" },
  { id: "ganadas", nombre: "Oportunidades ganadas", formato: "entero" },
  { id: "roleplays", nombre: "Promedio de role plays", formato: "decimal" },
  { id: "evalgerente", nombre: "Evaluación del gerente", formato: "decimal" },
  { id: "examen", nombre: "Calificación del examen final", formato: "entero" },
  { id: "tareas", nombre: "Avance del plan de trabajo (%)", formato: "entero" },
  { id: "manual", nombre: "Verificación manual del mentor", formato: "manual" },
];

const t = (...xs) => xs.map((texto, i) => ({ id: "t" + (i + 1), texto }));

export const PLANTILLA = {
  version: 1,

  meses: [
    { n: 1, nombre: "Fundamentos del vendedor externo", objetivo: "Construir base técnica, comercial y de disciplina. El participante deja de pensar en números de parte y empieza a pensar en aplicaciones y problemas de planta.", resultado: "Mapa de portafolio por aplicación, territorio definido, cuentas objetivo y rutina semanal instalada." },
    { n: 2, nombre: "Prospección y generación de oportunidades", objetivo: "Abrir puertas por cuenta propia y sostener conversaciones de descubrimiento dentro de planta.", resultado: "Motor de prospección funcionando y primeras oportunidades reales cargadas al CRM." },
    { n: 3, nombre: "Venta consultiva y desarrollo de oportunidades", objetivo: "Diagnosticar, cuantificar el impacto del problema y construir propuestas técnico-comerciales defendibles.", resultado: "Oportunidades calificadas con business case y propuestas presentadas en persona." },
    { n: 4, nombre: "Desarrollo de cuentas estratégicas", objetivo: "Pasar de un contacto a una red de contactos y de una venta a un plan de crecimiento por cuenta.", resultado: "Account Plans aprobados, multithreading real y oportunidades de cross y up-selling abiertas." },
    { n: 5, nombre: "Autonomía comercial", objetivo: "Administrar territorio, pipeline y forecast sin supervisión diaria.", resultado: "Territorio operado de forma autónoma, forecast confiable y dictamen de graduación." },
  ],

  semanas: [
    { id: "S1", mes: 1, titulo: "Rol del vendedor externo y portafolio aplicado",
      objetivo: "Entender qué cambia al vender dentro de una planta y dominar el portafolio de ISEL por problema que resuelve, no por marca.",
      tema: "Rol y expectativas · Ciclo comercial B2B industrial · Portafolio ISEL por aplicación",
      cap: "4 h con el gerente: diferencias entre venta interna y externa, ciclo largo, expectativas de actividad semanal. 8 h con especialistas por familia: SICK (seguridad de máquina y detección), R.STAHL (áreas clasificadas), ABB, Siemens, Rockwell, Delta e Invertek (control y variadores), Balluff y Panasonic (sensórica), Mech-Mind (visión), iluminación y señalización.",
      practica: "Construir la tabla maestra «familia → problema de planta que resuelve → pregunta que lo detecta → especialista de ISEL». Role play de 10 min: explicar qué hace ISEL a un jefe de mantenimiento sin usar números de parte ni nombres de marca.",
      real: "Clasificar las últimas 30 cotizaciones que él mismo trabajó por sector, aplicación y motivo real de compra. Llamar a 5 clientes actuales para preguntar para qué usaron lo que compraron.",
      kpi: "1 mapa de portafolio · 30 cotizaciones clasificadas · 5 llamadas a clientes actuales",
      evidencia: "Mapa de portafolio, matriz de cotizaciones y evaluación inicial de competencias firmada",
      resp: "Gerente comercial y especialistas técnicos",
      tasks: t("Sesión de expectativas del rol con el gerente", "Talleres técnicos por familia de producto", "Tabla producto → problema → pregunta → especialista", "Clasificación de 30 cotizaciones históricas", "5 llamadas a clientes actuales sobre uso real", "Evaluación inicial de competencias") },

    { id: "S2", mes: 1, titulo: "Aplicaciones industriales y lenguaje de negocio",
      objetivo: "Traducir un síntoma de planta en consecuencia operativa e impacto financiero.",
      tema: "Aplicaciones típicas · Cadena problema → consecuencia → impacto → prioridad",
      cap: "Taller de 6 h sobre 12 aplicaciones recurrentes: paros de línea, scrap, resguardo de operador, detección de presencia, obsolescencia de control, consumo energético en bombeo y ventilación, trazabilidad, inspección por visión, áreas clasificadas, arranques de motor, mantenimiento correctivo repetido y cambios de formato lentos. Introducción a costos de planta: costo de minuto parado, costo de pieza rechazada y costo de un accidente registrable.",
      practica: "Para cada aplicación, escribir la cadena completa: problema técnico → consecuencia operacional → impacto financiero anual estimado → a quién le duele. Role play: convertir «necesito una barrera de seguridad» en una conversación de riesgo, paro y costo.",
      real: "Recorrer 2 plantas de clientes actuales con el mentor y documentar 10 aplicaciones observadas con foto y descripción.",
      kpi: "12 cadenas de impacto escritas · 2 recorridos de planta · 10 aplicaciones documentadas",
      evidencia: "Cuaderno de aplicaciones con fotos, descripción y estimación de impacto",
      resp: "Mentor y especialista de aplicaciones",
      tasks: t("Taller de 12 aplicaciones industriales", "Cálculo de costo de minuto parado y de scrap", "12 cadenas problema → impacto redactadas", "2 recorridos de planta con el mentor", "Cuaderno de aplicaciones entregado") },

    { id: "S3", mes: 1, titulo: "ICP, segmentación y territorio",
      objetivo: "Definir a quién sí vale la pena visitar y armar el territorio con criterio, no por cercanía.",
      tema: "Perfil de cliente ideal · Segmentación por sector y proceso · Territorio y ruteo",
      cap: "Sesión de 3 h: construcción del ICP de ISEL (sector, tamaño, número de líneas, nivel de automatización, antigüedad de equipo, existencia de área de mantenimiento e ingeniería, gasto anual estimado). Fuentes de investigación: sitio web, LinkedIn, directorios industriales, parques industriales, notas de expansión y proveedores instalados.",
      practica: "Investigar 10 empresas y llenar una ficha de 12 datos por empresa. Defender ante el gerente por qué 3 de ellas son cuenta objetivo y 3 no lo son.",
      real: "Definir el territorio asignado y construir la lista de 40 cuentas objetivo priorizadas en A, B y C con criterio explícito.",
      kpi: "40 cuentas listadas · 20 fichas de investigación completas · 1 territorio definido",
      evidencia: "Lista de cuentas objetivo A/B/C con justificación y fichas de investigación",
      resp: "Gerente comercial",
      tasks: t("Definición del ICP de ISEL", "Investigación de 20 empresas con ficha completa", "Lista de 40 cuentas priorizadas A/B/C", "Defensa del criterio de priorización ante el gerente", "Ruta geográfica semanal propuesta") },

    { id: "S4", mes: 1, titulo: "Preparación de visitas, CRM y disciplina semanal",
      objetivo: "Instalar la rutina de trabajo del vendedor externo y la higiene de CRM desde el primer día.",
      tema: "Plan de visita · Registro en CRM · Agenda semanal · Reporte de actividad",
      cap: "3 h de CRM: qué es lead, prospecto, oportunidad y cuenta estratégica; campos obligatorios; qué no debe entrar al pipeline. 2 h de planeación: bloques de prospección, bloques de visita y bloque de administración.",
      practica: "Preparar 5 planes de visita completos (objetivo, hipótesis de aplicación, 8 preguntas, material, resultado esperado, siguiente paso comprometido). Simulación de cierre de día: registrar 3 visitas ficticias en CRM en menos de 10 minutos.",
      real: "Acompañar 4 visitas del mentor como observador y levantar el formato de revisión de visita en cada una.",
      kpi: "4 visitas observadas · 5 planes de visita · 100 % de registros en CRM el mismo día",
      evidencia: "Planes de visita, 4 formatos de revisión de visita y agenda semanal publicada",
      resp: "Mentor y gerente comercial",
      tasks: t("Capacitación de CRM y definiciones de embudo", "5 planes de visita preparados", "4 visitas observadas con formato levantado", "Agenda semanal por bloques publicada", "Evaluación de competencias del mes 1") },

    { id: "S5", mes: 2, titulo: "Motor de prospección: lista, secuencia y mensajes",
      objetivo: "Tener un sistema repetible de contacto en frío, no intentos aislados.",
      tema: "Secuencia multicanal · Mensajes por rol · Investigación previa al contacto",
      cap: "4 h: construcción de secuencia de 12 toques en 15 días hábiles (llamada, correo, LinkedIn, visita en frío y referido interno). Mensajes diferenciados para mantenimiento, ingeniería, producción, seguridad e higiene, calidad y compras.",
      practica: "Escribir 5 correos de prospección de menos de 120 palabras, uno por rol, cada uno anclado a una aplicación concreta. Revisión y reescritura con el gerente.",
      real: "Cargar 40 contactos nuevos al CRM e iniciar secuencia con 25 de ellos.",
      kpi: "40 contactos nuevos · 25 secuencias iniciadas · 5 plantillas aprobadas",
      evidencia: "Secuencia documentada, plantillas aprobadas y contactos en CRM",
      resp: "Gerente comercial",
      tasks: t("Diseño de la secuencia de 12 toques", "5 plantillas de correo por rol aprobadas", "Investigación de 40 contactos nuevos", "25 secuencias activas en CRM", "Revisión de mensajes con el gerente") },

    { id: "S6", mes: 2, titulo: "Llamada en frío y acceso a planta",
      objetivo: "Conseguir citas por teléfono y entrar a plantas donde ISEL no tiene relación.",
      tema: "Apertura en frío · Manejo de filtros · Objeciones de primer contacto · Acceso físico",
      cap: "3 h de técnica de llamada: apertura de 20 segundos anclada a un problema, permiso, pregunta de diagnóstico y cierre a cita. Guion de recepción y caseta. Manejo de «mándame información», «ya tenemos proveedor», «no hay presupuesto» y «no es mi área».",
      practica: "20 role plays grabados de llamada en frío con el gerente y el mentor, revisando al menos 5 grabaciones. Simulación de acceso por caseta.",
      real: "80 llamadas en frío reales y 5 visitas en frío a parques industriales del territorio.",
      kpi: "80 llamadas · 20 conversaciones significativas · 6 citas agendadas",
      evidencia: "Bitácora de llamadas, 5 grabaciones revisadas y citas en agenda",
      resp: "Gerente comercial y mentor",
      tasks: t("Taller de apertura en frío y manejo de filtros", "20 role plays de llamada", "5 grabaciones revisadas con el gerente", "80 llamadas en frío ejecutadas", "6 citas agendadas por cuenta propia") },

    { id: "S7", mes: 2, titulo: "LinkedIn, correo y construcción de agenda",
      objetivo: "Complementar el teléfono con canales digitales y llenar la agenda con visitas de calidad.",
      tema: "Perfil profesional · Social selling industrial · Redacción comercial · Confirmación de citas",
      cap: "2 h: optimización del perfil de LinkedIn orientado a resolver problemas de planta, búsqueda de organigramas y solicitud de conexión con contexto. 2 h: redacción comercial, asunto, prueba social y llamada a la acción de un solo paso.",
      practica: "Auditoría cruzada de perfiles con el mentor. Reescritura de 10 mensajes rechazados por el gerente.",
      real: "40 solicitudes de conexión con mensaje, 30 correos enviados y confirmación de todas las citas de la semana siguiente.",
      kpi: "40 conexiones solicitadas · 30 correos · 8 visitas agendadas para la semana siguiente",
      evidencia: "Perfil actualizado, reporte de respuestas y agenda confirmada",
      resp: "Gerente comercial",
      tasks: t("Optimización del perfil de LinkedIn", "40 solicitudes de conexión con contexto", "30 correos de prospección enviados", "Agenda de la semana siguiente confirmada", "Revisión de tasa de respuesta por canal") },

    { id: "S8", mes: 2, titulo: "Primeras visitas y recorrido de planta",
      objetivo: "Sostener una visita completa: apertura, recorrido, preguntas, hallazgos y siguiente paso comprometido.",
      tema: "Estructura de visita · Recorrido guiado · Observación de aplicaciones · Cierre de visita",
      cap: "3 h: qué mirar en un recorrido (tableros, guardas, paros, condición de sensores, obsolescencia, señalización, áreas clasificadas y cuellos de botella) y cómo preguntar sin parecer auditoría.",
      practica: "Role play de visita completa de 30 min con el mentor haciendo de jefe de mantenimiento hostil, con retroalimentación inmediata.",
      real: "12 visitas: 8 acompañadas por el mentor y 4 lideradas parcialmente por el participante, con formato de revisión en todas.",
      kpi: "12 visitas · 6 oportunidades detectadas · 12 formatos de visita completos",
      evidencia: "Formatos de revisión de visita y oportunidades cargadas en CRM",
      resp: "Mentor",
      tasks: t("Taller de recorrido de planta", "Role play de visita completa con retroalimentación", "8 visitas acompañadas", "4 visitas lideradas parcialmente", "6 oportunidades cargadas en CRM", "Evaluación de competencias del mes 2") },

    { id: "S9", mes: 3, titulo: "Discovery estructurado",
      objetivo: "Dirigir una conversación de diagnóstico con preguntas que descubran el problema real y no el pedido aparente.",
      tema: "SPIN aplicado a planta · Preguntas de situación, problema, implicación y beneficio · Escucha activa",
      cap: "4 h de metodología con casos de ISEL: banco de 60 preguntas clasificadas por rol y por aplicación, técnica de profundización en tres niveles y manejo del silencio.",
      practica: "8 role plays de discovery grabados, uno por perfil (mantenimiento, ingeniería, producción, seguridad, calidad, compras, gerente de planta y dirección). Evaluación con rúbrica: proporción de preguntas contra afirmaciones, profundidad y hallazgo cuantificado.",
      real: "10 visitas con discovery liderado por el participante y hallazgos documentados.",
      kpi: "10 discovery liderados · relación de preguntas y afirmaciones mayor a 2 a 1 · 8 pains cuantificables",
      evidencia: "Grabaciones o notas de discovery y rúbrica firmada por el mentor",
      resp: "Mentor y gerente comercial",
      tasks: t("Banco de 60 preguntas por rol y aplicación", "8 role plays de discovery evaluados con rúbrica", "10 discovery reales liderados", "Documentación de pains en CRM", "Retroalimentación grabación por grabación") },

    { id: "S10", mes: 3, titulo: "Cuantificación del impacto económico",
      objetivo: "Poner número al problema del cliente y usarlo para crear urgencia legítima.",
      tema: "Costo de paro, scrap, retrabajo, energía y riesgo · Business case simple · Retorno de inversión",
      cap: "4 h: modelo de cálculo de impacto (frecuencia por duración por costo unitario), estimación de ahorro por proyecto, cálculo de retorno de inversión en meses y sensibilidad de supuestos. Cómo validar supuestos con el cliente en vez de inventarlos.",
      practica: "Construir 3 business case a partir de hallazgos reales de sus propias visitas y presentarlos al comité interno que los cuestiona.",
      real: "Validar el impacto estimado con el cliente en al menos 4 oportunidades abiertas.",
      kpi: "3 business case construidos · 4 impactos validados con el cliente",
      evidencia: "Business case en formato ISEL con supuestos validados por el cliente",
      resp: "Gerente comercial y especialista técnico",
      tasks: t("Taller de cuantificación de impacto", "3 business case construidos y defendidos", "Validación de supuestos con 4 clientes", "Cálculo de retorno en oportunidades grandes", "Ajuste de propuesta de valor por caso") },

    { id: "S11", mes: 3, titulo: "Calificación de oportunidades y avance de etapa",
      objetivo: "Dejar de cargar el pipeline con humo. Cada oportunidad avanza solo con evidencia.",
      tema: "Criterios de calificación · Decisor, presupuesto, timing, competencia y riesgo · Higiene de pipeline",
      cap: "3 h: criterios objetivos de avance por etapa, probabilidad realista, fecha estimada de cierre defendible y definición de próxima acción con fecha y dueño. Cómo cerrar una oportunidad muerta a tiempo.",
      practica: "Auditoría de su propio pipeline: cada oportunidad debe pasar los criterios o retroceder de etapa. Defensa de 10 oportunidades ante el gerente en 30 minutos.",
      real: "Depurar el pipeline completo y recalificar todas las oportunidades abiertas.",
      kpi: "100 % de oportunidades con decisor, presupuesto, timing y próxima acción",
      evidencia: "Pipeline auditado y acta de depuración",
      resp: "Gerente comercial",
      tasks: t("Taller de criterios de avance por etapa", "Auditoría del pipeline propio", "Defensa de 10 oportunidades ante el gerente", "Depuración de oportunidades muertas", "Registro completo de campos obligatorios") },

    { id: "S12", mes: 3, titulo: "Propuesta técnico-comercial y presentación",
      objetivo: "Construir y presentar una solución, no enviar una cotización.",
      tema: "Estructura de propuesta · Coordinación con el especialista · Presentación en sitio · Manejo de objeciones",
      cap: "3 h: estructura de propuesta (problema del cliente en sus palabras, impacto, solución, alcance, entregables, retorno, plan de implementación y siguiente paso). 2 h: cómo dar el brief al especialista para que su tiempo rinda.",
      practica: "3 presentaciones simuladas de 15 min ante panel interno con objeciones planeadas de precio, plazo, marca y riesgo técnico.",
      real: "Presentar 3 propuestas reales en sitio, con especialista cuando aplique, y cerrar cada una con siguiente paso y fecha.",
      kpi: "3 propuestas presentadas en persona · 100 % con siguiente paso agendado · 8 cotizaciones enviadas",
      evidencia: "Propuestas en formato ISEL y minutas de presentación",
      resp: "Gerente comercial y especialistas",
      tasks: t("Taller de estructura de propuesta", "Brief efectivo al especialista técnico", "3 presentaciones simuladas ante panel", "3 propuestas presentadas en sitio", "Evaluación de competencias del mes 3") },

    { id: "S13", mes: 4, titulo: "Account mapping: planta, proceso y tecnología instalada",
      objetivo: "Conocer una cuenta grande mejor que el competidor que ya está adentro.",
      tema: "Mapa de procesos · Tecnología instalada · Áreas con potencial · Competidores presentes",
      cap: "3 h: cómo levantar el mapa de una planta (líneas, procesos, criticidad, turnos, plan de inversión, obsolescencia y proyectos de expansión) y cómo detectar marca instalada y contratos vigentes.",
      practica: "Mapear en pizarrón 2 cuentas reales con el mentor y detectar los 5 huecos de oportunidad más probables en cada una.",
      real: "Levantar el mapa de 3 cuentas objetivo con visita física a cada una.",
      kpi: "3 cuentas mapeadas · 15 oportunidades potenciales identificadas",
      evidencia: "Mapas de cuenta con procesos, tecnología y huecos de oportunidad",
      resp: "Mentor y gerente comercial",
      tasks: t("Taller de mapeo de planta", "Mapeo en pizarrón de 2 cuentas reales", "3 mapas de cuenta levantados en campo", "Identificación de competidores instalados", "Lista de huecos de oportunidad por cuenta") },

    { id: "S14", mes: 4, titulo: "Stakeholders, champions y multithreading",
      objetivo: "Pasar de un contacto a una red de contactos con poder de decisión.",
      tema: "Organigrama · Influencia contra autoridad · Champion, usuario, técnico, económico y detractor",
      cap: "3 h: construcción de organigrama comercial, matriz de influencia y poder, señales de un champion real contra un contacto amable, y estrategia para neutralizar detractores y entrar por arriba sin quemar al contacto operativo.",
      practica: "Role play de reunión con gerente de planta pedida por referencia interna. Plan de entrada a 3 niveles para 2 cuentas.",
      real: "Sumar 15 stakeholders nuevos en cuentas existentes y sostener al menos 5 reuniones con áreas con las que ISEL no hablaba antes.",
      kpi: "15 stakeholders nuevos · 5 reuniones con áreas nuevas · 2 champions validados",
      evidencia: "Mapas de stakeholders con influencia, decisión y relación actual",
      resp: "Mentor",
      tasks: t("Taller de mapeo de stakeholders", "Matriz de influencia y poder por cuenta", "15 stakeholders nuevos registrados", "5 reuniones con áreas nuevas", "Validación de 2 champions con el gerente") },

    { id: "S15", mes: 4, titulo: "Cross-selling, up-selling y crecimiento de cuenta",
      objetivo: "Convertir una venta puntual en un plan de crecimiento con secuencia y calendario.",
      tema: "Portafolio cruzado · Plan de crecimiento · De proveedor eventual a proveedor frecuente",
      cap: "3 h: análisis de participación en la cuenta, mapa de siguientes compras lógicas por aplicación, calendario de contacto por rol y uso de proyectos pequeños como puerta a proyectos grandes.",
      practica: "Diseñar el plan de crecimiento a 12 meses de 2 cuentas, con oportunidades secuenciadas y valor estimado por trimestre.",
      real: "Abrir al menos 4 oportunidades de cross o up-selling en cuentas donde ISEL ya vende una sola línea.",
      kpi: "4 oportunidades de cross o up-selling · 2 planes de crecimiento a 12 meses",
      evidencia: "Planes de crecimiento por cuenta con oportunidades secuenciadas",
      resp: "Gerente comercial",
      tasks: t("Análisis de participación por cuenta", "2 planes de crecimiento a 12 meses", "4 oportunidades de cross o up-selling abiertas", "Calendario de contacto por rol", "Revisión de plan con el gerente") },

    { id: "S16", mes: 4, titulo: "Account Plan ejecutivo y negociación con compras",
      objetivo: "Presentar la cuenta como un negocio y defender valor frente a compras.",
      tema: "Account Plan completo · Comunicación ejecutiva · Negociación de valor · Concesiones",
      cap: "3 h: cómo presentar a dirección en 10 minutos. 3 h de negociación: preparación, rango de concesión, moneda de intercambio distinta al precio, tácticas de compras y cómo responderlas sin ceder margen.",
      practica: "Presentación de 2 Account Plans ante gerente y dirección. 4 role plays de negociación con comprador industrial exigente.",
      real: "Negociar al menos 2 oportunidades reales en etapa avanzada acompañado por el gerente.",
      kpi: "2 Account Plans aprobados · 2 negociaciones reales · margen dentro de política",
      evidencia: "Account Plans aprobados y minutas de negociación",
      resp: "Gerente comercial y dirección",
      tasks: t("Preparación de 2 Account Plans", "Presentación ejecutiva ante dirección", "4 role plays de negociación", "2 negociaciones reales acompañadas", "Evaluación de competencias del mes 4") },

    { id: "S17", mes: 5, titulo: "Planeación territorial y semana autónoma",
      objetivo: "Administrar su tiempo y su territorio sin que nadie le arme la agenda.",
      tema: "Planeación semanal · Ruteo · Bloques de actividad · Priorización de cuentas",
      cap: "2 h: planeación por objetivos semanales, regla de cobertura del territorio, distribución entre cuentas nuevas y cuentas en desarrollo, y control de la semana con tablero propio.",
      practica: "Planear la semana completa y defenderla ante el gerente antes de ejecutarla; comparar plan contra ejecución el viernes.",
      real: "Semana operada con agenda propia: 6 visitas, prospección diaria y actualización de CRM el mismo día.",
      kpi: "6 visitas · cumplimiento del plan semanal mayor a 85 % · CRM al día",
      evidencia: "Plan semanal y reporte de cumplimiento de plan contra real",
      resp: "Participante con supervisión del gerente",
      tasks: t("Plan semanal defendido antes de ejecutar", "6 visitas ejecutadas con agenda propia", "Prospección diaria sostenida", "Comparativo de plan contra real del viernes", "Ajuste de ruteo por territorio") },

    { id: "S18", mes: 5, titulo: "Ejecución autónoma y forecast",
      objetivo: "Comprometer números y sostenerlos con evidencia.",
      tema: "Forecast mensual y trimestral · Probabilidad realista · Riesgos por oportunidad",
      cap: "2 h: cómo se arma un forecast, diferencia entre pipeline y compromiso, categorías de confianza y señales de que una fecha de cierre no es real.",
      practica: "Presentar forecast del mes y del trimestre ante el gerente y sostenerlo con evidencia oportunidad por oportunidad.",
      real: "Territorio operado de forma autónoma: visitas, prospección, avance de oportunidades y actualización de forecast semanal.",
      kpi: "Precisión de forecast dentro de 20 % · 6 visitas · 4 oportunidades avanzadas de etapa",
      evidencia: "Forecast documentado y comparativo contra resultado real",
      resp: "Participante con revisión del gerente",
      tasks: t("Taller de forecast", "Forecast mensual presentado y defendido", "6 visitas autónomas", "4 oportunidades avanzadas de etapa", "Actualización semanal del forecast") },

    { id: "S19", mes: 5, titulo: "Negociación, cierre y recuperación",
      objetivo: "Cerrar y también rescatar lo que se estancó.",
      tema: "Cierre · Manejo de objeciones tardías · Reactivación de oportunidades frías · Post-venta",
      cap: "2 h: técnicas de cierre por compromiso progresivo, manejo de la última objeción, qué hacer cuando el proyecto se pospone y cómo pedir la orden sin incomodar la relación.",
      practica: "4 role plays de cierre difícil y 2 de reactivación de oportunidad congelada.",
      real: "Cerrar al menos 1 proyecto o aplicación nueva y reactivar 3 oportunidades detenidas.",
      kpi: "1 cierre nuevo · 3 oportunidades reactivadas · 6 visitas",
      evidencia: "Orden de compra o compromiso formal y bitácora de reactivación",
      resp: "Participante y gerente comercial",
      tasks: t("4 role plays de cierre difícil", "2 role plays de reactivación", "3 oportunidades reactivadas", "1 cierre de aplicación o proyecto nuevo", "Plan de post-venta y seguimiento de entrega") },

    { id: "S20", mes: 5, titulo: "Evaluación final y graduación",
      objetivo: "Demostrar dominio y recibir dictamen.",
      tema: "Examen integral · Revisión de evidencia · Dictamen y plan de 90 días",
      cap: "Repaso guiado y preparación del expediente de evidencia.",
      practica: "Evaluación final: conocimiento, role play de discovery, caso práctico, presentación de solución, análisis de cuenta y revisión de pipeline.",
      real: "Presentación del territorio completo, pipeline, forecast y Account Plans ante gerente y dirección.",
      kpi: "Calificación final mayor o igual a 85 · scorecard mayor o igual a 4.0",
      evidencia: "Expediente completo y acta de dictamen firmada",
      resp: "Gerente comercial y dirección",
      tasks: t("Preparación del expediente de evidencia", "Examen de conocimiento", "Role play de discovery evaluado", "Caso práctico y presentación de solución", "Análisis de cuenta y revisión de pipeline", "Dictamen de graduación firmado", "Plan de 90 días posteriores acordado") },
  ],

  grupos: [
    { id: "g1", nombre: "Competencias comerciales", peso: 10 },
    { id: "g2", nombre: "Competencias técnicas", peso: 10 },
    { id: "g3", nombre: "Prospección", peso: 12 },
    { id: "g4", nombre: "Venta consultiva", peso: 15 },
    { id: "g5", nombre: "Desarrollo de oportunidades", peso: 12 },
    { id: "g6", nombre: "Desarrollo de cuentas", peso: 12 },
    { id: "g7", nombre: "Negociación", peso: 8 },
    { id: "g8", nombre: "CRM y pipeline", peso: 8 },
    { id: "g9", nombre: "Organización y territorio", peso: 5 },
    { id: "g10", nombre: "Comunicación", peso: 4 },
    { id: "g11", nombre: "Competencias conductuales", peso: 4 },
  ],

  competencias: [
    ["c01","g1","Rol del vendedor externo y autonomía",1,4,"Crítica","Observación en campo y cumplimiento del plan semanal"],
    ["c02","g1","Conocimiento aplicado del portafolio ISEL",2,4,"Crítica","Examen técnico y defensa de aplicaciones ante especialista"],
    ["c03","g1","Segmentación e ICP",1,4,"Alta","Calidad y justificación de la lista de cuentas objetivo"],
    ["c04","g2","Lectura de aplicaciones en planta",1,4,"Crítica","Hallazgos documentados por visita y validación del mentor"],
    ["c05","g2","Traducción de problema técnico a impacto de negocio",1,4,"Crítica","Business case revisado por el gerente"],
    ["c06","g2","Involucrar al especialista correcto y dar buen brief",1,4,"Alta","Retroalimentación de especialistas técnicos"],
    ["c07","g3","Investigación de empresas y plantas",2,4,"Alta","Fichas de investigación y mapas de cuenta"],
    ["c08","g3","Construcción de lista y territorio",1,4,"Alta","Lista A/B/C y cobertura real del territorio"],
    ["c09","g3","Llamada en frío",1,4,"Crítica","Grabaciones evaluadas con rúbrica y citas obtenidas"],
    ["c10","g3","Prospección por correo y LinkedIn",2,4,"Media","Tasa de respuesta y calidad de mensajes"],
    ["c11","g3","Apertura de puertas y acceso a planta",1,4,"Crítica","Visitas a cuentas nuevas conseguidas por cuenta propia"],
    ["c12","g4","Preparación de visita",2,5,"Alta","Plan de visita previo y revisión del mentor"],
    ["c13","g4","Recorrido de planta",1,4,"Crítica","Aplicaciones detectadas por recorrido"],
    ["c14","g4","Discovery y preguntas de diagnóstico",1,5,"Crítica","Role play grabado con rúbrica y hallazgos reales"],
    ["c15","g4","Escucha activa",2,4,"Alta","Rúbrica de role play y notas de visita"],
    ["c16","g4","Identificación de pain points",1,4,"Crítica","Pains documentados y validados con el cliente"],
    ["c17","g4","Cuantificación del impacto económico",1,4,"Crítica","Business case con supuestos validados"],
    ["c18","g4","Manejo de objeciones",2,4,"Alta","Role plays y resultado de visitas difíciles"],
    ["c19","g5","Calificación de oportunidades",1,4,"Crítica","Auditoría de pipeline"],
    ["c20","g5","Construcción de business case",1,4,"Alta","Propuestas con retorno calculado"],
    ["c21","g5","Propuesta técnico-comercial",2,4,"Alta","Calidad de propuesta y tasa de avance de etapa"],
    ["c22","g5","Presentación comercial",1,4,"Alta","Presentaciones ante panel y ante cliente"],
    ["c23","g5","Seguimiento profesional",3,5,"Alta","Próxima acción vigente en todas las oportunidades"],
    ["c24","g6","Account mapping",1,4,"Crítica","Mapas de cuenta completos"],
    ["c25","g6","Stakeholder mapping y multithreading",1,4,"Crítica","Contactos nuevos por cuenta y áreas alcanzadas"],
    ["c26","g6","Desarrollo de champions",1,4,"Alta","Champions validados por el gerente"],
    ["c27","g6","Cross-selling y up-selling",1,4,"Alta","Oportunidades abiertas en líneas nuevas"],
    ["c28","g6","Account Plan y plan de crecimiento",1,4,"Crítica","Account Plans aprobados por dirección"],
    ["c29","g7","Negociación de valor",1,4,"Crítica","Role plays y margen defendido"],
    ["c30","g7","Manejo de compras",1,4,"Alta","Resultado de negociaciones reales"],
    ["c31","g8","Higiene y uso del CRM",2,5,"Alta","Auditoría de registros y oportunidad del registro"],
    ["c32","g8","Gestión de pipeline",1,4,"Crítica","Pipeline auditado sin oportunidades vencidas"],
    ["c33","g8","Forecast",1,4,"Alta","Precisión de forecast contra resultado real"],
    ["c34","g9","Planeación territorial y semanal",1,4,"Alta","Cumplimiento de plan contra real"],
    ["c35","g9","Gestión del tiempo",2,4,"Media","Proporción de tiempo en campo contra escritorio"],
    ["c36","g10","Comunicación ejecutiva",1,4,"Alta","Presentación ante dirección"],
    ["c37","g10","Comunicación escrita comercial",2,4,"Media","Correos, minutas y propuestas"],
    ["c38","g11","Iniciativa y proactividad",2,5,"Crítica","Actividad generada sin instrucción"],
    ["c39","g11","Disciplina comercial",2,5,"Crítica","Consistencia semanal de indicadores de actividad"],
    ["c40","g11","Resiliencia ante el rechazo",2,4,"Crítica","Sostenimiento de actividad tras semanas de baja conversión"],
    ["c41","g11","Curiosidad y pensamiento analítico",2,4,"Alta","Profundidad de hallazgos y calidad de preguntas"],
    ["c42","g11","Orientación a resultados",2,4,"Alta","Cumplimiento de metas mensuales"],
  ].map(([id, grupo, nombre, ini, req, imp, evalua]) => ({ id, grupo, nombre, ini, req, imp, evalua })),

  kpis: [
    { id: "k01", nombre: "Prospectos investigados", tipo: "Leading", unidad: "cantidad", metas: [20, 40, 40, 30, 30], logica: "Alto al inicio para construir territorio; baja al madurar la cartera." },
    { id: "k02", nombre: "Contactos nuevos", tipo: "Leading", unidad: "cantidad", metas: [10, 30, 30, 25, 25], logica: "El motor de prospección arranca en el mes 2." },
    { id: "k03", nombre: "Conversaciones significativas", tipo: "Leading", unidad: "cantidad", metas: [5, 20, 25, 25, 25], logica: "Conversación con hallazgo, no solo contacto." },
    { id: "k04", nombre: "Visitas totales", tipo: "Leading", unidad: "cantidad", metas: [8, 16, 20, 20, 24], logica: "Progresión de observador a seis visitas semanales autónomas." },
    { id: "k05", nombre: "Visitas a cuentas nuevas", tipo: "Leading", unidad: "cantidad", metas: [2, 8, 8, 6, 6], logica: "Evita que se refugie en la cartera existente." },
    { id: "k06", nombre: "Oportunidades detectadas", tipo: "Leading", unidad: "cantidad", metas: [2, 6, 8, 8, 10], logica: "Una visita bien hecha produce entre 0.4 y 0.5 oportunidades." },
    { id: "k07", nombre: "Oportunidades calificadas", tipo: "Leading", unidad: "cantidad", metas: [0, 2, 4, 5, 6], logica: "Calificar exige decisor, presupuesto y timing; toma tiempo." },
    { id: "k08", nombre: "Cotizaciones enviadas", tipo: "Leading", unidad: "cantidad", metas: [2, 6, 8, 10, 12], logica: "Incluye cotización derivada de aplicación, no solo de lista de partes." },
    { id: "k09", nombre: "Pipeline generado", tipo: "Leading", unidad: "dinero", metas: [150000, 400000, 800000, 1200000, 1500000], logica: "Ticket promedio industrial de 60 000 a 250 000 MXN." },
    { id: "k10", nombre: "Pipeline calificado", tipo: "Leading", unidad: "dinero", metas: [0, 150000, 400000, 700000, 900000], logica: "Solo lo que pasó criterios de calificación." },
    { id: "k11", nombre: "Stakeholders nuevos", tipo: "Leading", unidad: "cantidad", metas: [5, 12, 15, 20, 20], logica: "Mide multithreading real, no cantidad de tarjetas." },
    { id: "k12", nombre: "Cuentas mapeadas", tipo: "Leading", unidad: "cantidad", metas: [1, 2, 3, 4, 2], logica: "Mapear bien doce cuentas vale más que tocar sesenta." },
    { id: "k13", nombre: "Account Plans entregados", tipo: "Leading", unidad: "cantidad", metas: [0, 0, 1, 2, 1], logica: "Aparece cuando ya hay información suficiente para planear." },
    { id: "k14", nombre: "Ventas cerradas", tipo: "Lagging", unidad: "dinero", metas: [0, 50000, 150000, 300000, 400000], logica: "Ciclo de seis a dieciséis semanas: los cierres del mes 5 vienen de la prospección del mes 2." },
  ],

  planVisitas: [
    { mes: 1, observa: 6, acompanado: 2, lidera: 0, autonoma: 0 },
    { mes: 2, observa: 4, acompanado: 8, lidera: 4, autonoma: 0 },
    { mes: 3, observa: 2, acompanado: 6, lidera: 10, autonoma: 2 },
    { mes: 4, observa: 0, acompanado: 4, lidera: 8, autonoma: 8 },
    { mes: 5, observa: 0, acompanado: 2, lidera: 4, autonoma: 18 },
  ],

  etapas: [
    { id: "nueva", nombre: "Nueva oportunidad", prob: 10, criterios: ["Necesidad expresada por el cliente, no supuesta", "Aplicación identificada y descrita", "Contacto con quien vive el problema", "Impacto estimado aunque sea preliminar", "Próxima acción con fecha"] },
    { id: "calificada", nombre: "Calificada", prob: 30, criterios: ["Impacto económico validado con el cliente", "Decisor identificado por nombre y puesto", "Ruta de presupuesto confirmada", "Timing declarado por el cliente", "Competencia conocida", "Alcance técnico revisado con especialista"] },
    { id: "cotizacion", nombre: "Cotización", prob: 50, criterios: ["Propuesta presentada en persona", "Solución validada técnicamente", "Retorno o justificación entregada", "Objeciones documentadas", "Fecha de decisión acordada"] },
    { id: "negociacion", nombre: "Negociación", prob: 75, criterios: ["Champion activo dentro de la cuenta", "Condiciones comerciales en discusión", "Ruta de orden de compra conocida", "Riesgos identificados con plan de mitigación"] },
    { id: "ganada", nombre: "Ganada", prob: 100, criterios: ["Orden de compra o compromiso formal recibido", "Plan de entrega acordado"] },
    { id: "perdida", nombre: "Perdida", prob: 0, criterios: ["Motivo de pérdida documentado", "Aprendizaje registrado", "Fecha de reactivación definida"] },
  ],

  criterios: [
    { id: "x1",  nombre: "Scorecard ponderado", fuente: "scorecard", meta: 4, puntos: 20 },
    { id: "x2",  nombre: "Competencias críticas por debajo del nivel requerido", fuente: "criticas", meta: 0, puntos: 15 },
    { id: "x3",  nombre: "Visitas acumuladas", fuente: "visitas", meta: 80, puntos: 8 },
    { id: "x4",  nombre: "Visitas lideradas solo", fuente: "visitas_solo", meta: 30, puntos: 8 },
    { id: "x5",  nombre: "Oportunidades detectadas", fuente: "opps", meta: 30, puntos: 7 },
    { id: "x6",  nombre: "Pipeline calificado", fuente: "pipeline_cal", meta: 2000000, puntos: 8 },
    { id: "x7",  nombre: "Cuentas mapeadas", fuente: "cuentas", meta: 8, puntos: 6 },
    { id: "x8",  nombre: "Account Plans aprobados", fuente: "planes", meta: 4, puntos: 6 },
    { id: "x9",  nombre: "Cierres nuevos", fuente: "ganadas", meta: 1, puntos: 5 },
    { id: "x10", nombre: "Promedio de role plays", fuente: "roleplays", meta: 4, puntos: 5 },
    { id: "x11", nombre: "Evaluación del gerente", fuente: "evalgerente", meta: 4, puntos: 6 },
    { id: "x12", nombre: "Examen final", fuente: "examen", meta: 85, puntos: 6 },
  ],

  umbrales: { apto: 85, aptoPlan: 65, scoreApto: 4, scorePlan: 3.5 },

  examen: [
    { id: "e1", nombre: "Conocimiento de portafolio y aplicaciones", peso: 15 },
    { id: "e2", nombre: "Role play de discovery", peso: 20 },
    { id: "e3", nombre: "Caso práctico de aplicación industrial", peso: 15 },
    { id: "e4", nombre: "Presentación de solución con retorno", peso: 15 },
    { id: "e5", nombre: "Análisis y defensa de una cuenta", peso: 15 },
    { id: "e6", nombre: "Revisión de pipeline y forecast", peso: 10 },
    { id: "e7", nombre: "Evidencia real de actividad comercial", peso: 10 },
  ],

  riesgos: [
    { id: "r1", riesgo: "Se refugia en el escritorio", senal: "Menos de cuatro visitas por semana a partir del mes 3 y muchas horas cotizando.", accion: "Bloquear agenda: martes a jueves solo campo. El gerente revisa la agenda cada lunes y el reporte de visitas cada viernes." },
    { id: "r2", riesgo: "Sigue actuando como tomador de pedidos", senal: "Todas sus oportunidades vienen de solicitudes del cliente, ninguna fue creada por él.", accion: "Medir por separado oportunidades reactivas y creadas. Exigir un mínimo de 60 % creadas a partir del mes 3." },
    { id: "r3", riesgo: "No resiste el rechazo del contacto en frío", senal: "Cae la actividad de prospección después de una semana mala.", accion: "Prospección diaria en bloque fijo con el gerente presente las dos primeras semanas y reconocimiento de indicadores de actividad, no solo de cierres." },
    { id: "r4", riesgo: "Vende producto, no aplicación", senal: "En las visitas habla de marcas y modelos; los formatos de visita no tienen pains ni impacto.", accion: "Rúbrica de visita que exige pain, impacto y aplicación. Revisión semanal de grabaciones de discovery hasta el mes 3." },
    { id: "r5", riesgo: "Pipeline inflado", senal: "Oportunidades sin decisor, sin presupuesto y con fechas de cierre que se recorren cada mes.", accion: "Auditoría quincenal de pipeline con criterios objetivos. Toda oportunidad sin próxima acción vigente se retrocede o se cierra." },
    { id: "r6", riesgo: "Se queda en un solo contacto por cuenta", senal: "Cuentas con un único stakeholder registrado después del mes 3.", accion: "Meta explícita de stakeholders nuevos por mes y revisión mensual de cuenta con el mapa en la mesa." },
    { id: "r7", riesgo: "Depende del especialista técnico para todo", senal: "No sostiene una conversación técnica de primer nivel ni prepara el brief del especialista.", accion: "Certificación técnica interna por familia y regla de que el especialista solo entra después de un discovery documentado." },
    { id: "r8", riesgo: "Mala gestión del tiempo y del territorio", senal: "Rutas improvisadas, visitas dispersas y semanas sin plan.", accion: "Plan semanal por escrito los lunes y comparativo de plan contra real los viernes durante todo el programa." },
    { id: "r9", riesgo: "El mentor no tiene tiempo real para acompañarlo", senal: "Visitas acompañadas canceladas o pospuestas más de dos veces al mes.", accion: "Formalizar el rol del mentor con tiempo asignado, incentivo ligado a la graduación y mentor suplente designado." },
    { id: "r10", riesgo: "Se desmotiva porque no cierra en los primeros meses", senal: "Comentarios sobre falta de resultados, baja de energía y menos iniciativa.", accion: "Explicar desde el día uno el ciclo comercial de seis a dieciséis semanas, evaluar por indicadores leading en los meses 1 a 3 y proteger su compensación durante la transición." },
  ],

  plan90: [
    { bloque: "Días 1 a 30", foco: "Consolidar la rutina sin red de apoyo", acciones: ["Territorio y cartera formalmente asignados con metas por escrito", "Seis visitas semanales y prospección diaria sostenidas", "Pipeline propio con higiene total", "Una revisión semanal de pipeline con el gerente", "Dos acompañamientos de campo en el mes"] },
    { bloque: "Días 31 a 60", foco: "Convertir actividad en cierres", acciones: ["Cerrar al menos dos proyectos o aplicaciones nuevas", "Presentar tres propuestas con retorno calculado", "Actualizar los Account Plans de las cuentas A", "Abrir dos cuentas nuevas del ICP", "Forecast mensual dentro de 20 %"] },
    { bloque: "Días 61 a 90", foco: "Crecer cuentas y estabilizar el forecast", acciones: ["Subir al menos una cuenta de nivel de madurez", "Cross-selling en tres cuentas existentes", "Revisión de desempeño con dirección", "Definir metas anuales y plan de territorio a 12 meses", "Iniciar acompañamiento a un nuevo participante del programa"] },
  ],

  roles: [
    { rol: "Gerente comercial", resp: ["Dueño del programa y del dictamen final", "Sesión individual semanal de 45 minutos con agenda fija", "Revisión de pipeline semanal", "Acompañamiento de campo quincenal con formato de retroalimentación", "Evaluación mensual de competencias", "Aprobación de Account Plans y de metas mensuales", "Protege el tiempo del participante frente a tareas administrativas"] },
    { rol: "Mentor o vendedor externo senior", resp: ["Recibe al participante en sus visitas durante los meses 1 y 2", "Dos jornadas de campo por semana en los meses 1 y 2, una por semana después", "Retroalimentación inmediata al salir de cada planta", "Enseña acceso a planta, recorrido y lectura de aplicaciones", "Retroalimenta role plays de discovery"] },
    { rol: "Especialistas técnicos", resp: ["Capacitación por familia en el mes 1 y refuerzos mensuales", "Validación técnica de alcances y propuestas", "Retroalimentación sobre la calidad del brief que reciben", "Acompañamiento a visitas técnicas cuando el discovery ya está documentado"] },
    { rol: "Participante", resp: ["Ejecuta el plan semanal y lo reporta sin que se lo pidan", "Registra toda la actividad el mismo día", "Prepara cada visita por escrito antes de salir", "Lleva su expediente de evidencia al día", "Pide ayuda temprano cuando una oportunidad se atora"] },
  ],

  cadencia: [
    { actividad: "Sesión individual del gerente con el participante", frecuencia: "Semanal, 45 minutos", mes: "Meses 1 a 5" },
    { actividad: "Revisión de pipeline", frecuencia: "Semanal", mes: "Desde el mes 2" },
    { actividad: "Acompañamiento de campo del gerente", frecuencia: "Quincenal", mes: "Meses 1 a 5" },
    { actividad: "Jornada de campo con el mentor", frecuencia: "Dos por semana", mes: "Meses 1 y 2" },
    { actividad: "Jornada de campo con el mentor", frecuencia: "Una por semana", mes: "Meses 3 a 5" },
    { actividad: "Revisión de grabaciones y role play", frecuencia: "Semanal", mes: "Meses 1 a 3" },
    { actividad: "Revisión de cuenta", frecuencia: "Mensual", mes: "Desde el mes 3" },
    { actividad: "Evaluación de competencias", frecuencia: "Mensual", mes: "Meses 1 a 5" },
  ],
};

export const clonarPlantilla = () => JSON.parse(JSON.stringify(PLANTILLA));
